### ISSUE TITLE
Adding Content

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-content#15]
This isn't really an issue, more of a question for @RobLoach 
Is there appetite to add content to this repository via pull requests?  There's a host of public domain games for many of the systems listed here, but I'm unsure if this is more of a curated list of content or if theres an ability to add more.  If it's the latter, I could create some pull requests and reference the source to ensure its meeting public domain / shareware / licensing reqts.  An example would be [MAMEs PD ](https://www.mamedev.org/roms/) games.

Thanks in advance

**Comment by RobLoach** [comment]
Could add some of the most popular ones, yes. It's a good place to have some demo content for testing. Don't want to go overboard on it though. Just the ones you'd consider best or most popular.

We've gotten written permission from the original authors, and included liceneses, when needed too. For PD stuff, permission isn't needed. [Mystery House](https://en.wikipedia.org/wiki/Mystery_House) is an example of a PD game we've included for ScummVM.

**Comment by hizzlekizzle** [comment]
I looked into adding those PD MAME ROMs in the past, but decided not to based on this:

> Note: The ROMs on these pages have been approved for free distribution on this site only. Just because they are available here for download does not entitle you to put them on your own site, include them with your own distributions of MAME, or bundle them with your software, cabinet, or other item. To do that, you must obtain permission from the original owners.

**Comment by zach-morris** [comment]
Thanks,  no sense in leaving this open i guess.  If there are items i find that meet that criteria i'll send a pr
